name: Install Check

on:
  push:
    branches:
      - main

jobs:
  install-check:
    runs-on: ubuntu-latest

    steps:
      ### 1. Pobierz kod z repozytorium ###
      - name: Checkout repository
        uses: actions/checkout@v3

      ### 2. Ustaw Python 3.12.4 ###
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      ### 3. Zainstaluj zależności Pythonowe ###
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            greenlet>=3.0.3 \
            playwright==1.52.0 \
            pytest==8.3.5

      ### 4. Pobierz silniki Playwright wraz z zależnościami systemowymi ###
      - name: Install Playwright browsers and system dependencies
        run: python -m playwright install --with-deps

      ### 5. Zweryfikuj, że katalog z silnikami istnieje ###
      - name: List installed browsers
        run: ls -R ~/.cache/ms-playwrigh