# .github/workflows/ci-install-check.yml
name: Install Check

on:
  push:
    branches:
      - main

jobs:
  install-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            greenlet>=3.0.3 \
            playwright==1.52.0 \
            pytest==8.3.5

      - name: Install Playwright browsers and deps
        run: python -m playwright install --with-deps

      - name: Dump ~/.cache directory
        run: |
          echo "Contents of ~/.cache:"
          ls -R ~/.cache

      - name: Dump possible Playwright cache dirs
        run: |
          for d in ms-playwright playwright ms-playwright-chromium ms-playwright-firefox ms-playwright-webkit; do
            echo "--- ~/.cache/$d ---"
            ls -lah ~/.cache/$d || echo "No ~/.cache/$d"
          done