#### Nazwa workflow  ###
name: CI

### wywołanie workflows na push i pull requesty ###
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      ### odpala ten sam zestaw kroków równolegle ###
      matrix:
        ### przeglądarki Playwright ###
        browser: [chromium, firefox, webkit]

    steps:
      ### checkout kodu z repo ###
      - uses: actions/checkout@v3

      ### ustaw Pythona ###
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      ### instalacja zależności Pythonowych ###
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest

      ### użyj oficjalnego action by zainstalować silniki + zależności systemowe ###
      - name: Playwright install deps and browsers
        uses: microsoft/playwright-github-action@v1
        run: python -m playwright install

      ### uruchom testy dla wybranej przeglądarki ###
      - name: Run tests on ${{ matrix.browser }}
        run: pytest -q tests/zgoda_na_cookies.py
        ### przekazujemy browser jako zmienna środowiskowa ###
        env:
          BROWSER: ${{ matrix.browser }}
