# .github/workflows/ci-playwright.yml
name: Playwright CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Pobierz repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Zainstaluj Node.js (potrzebne do npx)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Zainstaluj Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 4. Zainstaluj zależności Pythonowe
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest

      # 5. Zainstaluj silniki i deps systemowe dla Playwright
      - name: Install Playwright browsers and deps
        uses: microsoft/playwright-github-action@v1

      # 6. Uruchom test w Chromium
      - name: Run test in Chromium
        env:
          BROWSER: chromium
        run: pytest -q tests/zgoda_na_cookies.py

      # 7. Uruchom test w Firefox
      - name: Run test in Firefox
        env:
          BROWSER: firefox
        run: pytest -q tests/zgoda_na_cookies.py

      # 8. Uruchom test w WebKit
      - name: Run test in WebKit
        env:
          BROWSER: webkit
        run: pytest -q tests/zgoda_na_cookies.py