#### Nazwa workflow  ###
name: CI

### wywolanie workflows na push i pull requesty ###
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      ### odpala ten sam zestaw krokow rownolegle ###
      matrix:
        ### przegladarki Playwright ###
        browser: [chromium, firefox, webkit]

    steps:
      ### checkout kodu z repo ###
      - uses: actions/checkout@v3

      ### ustaw pythona ###
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      ### zainstaluj zaleznosci ###
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest
          python -m playwright install

        ### uruchom testy dla wybranej przegladrki ###
      - name: Run tests on ${{ matrix.browser }}
        run: pytest -q tests/zgoda_na_cookies.py
        ### przekazujemy browser jako zmienna srodowiskowa ###
        env:
          BROWSER: ${{ matrix.browser }}