name: Smoke CI

on:
  push:
    branches:
      - main

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Smoke test
        run: echo "CI działa poprawnie!"