name: CI on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "greenlet>=3.0.3" "playwright==1.52.0" "pytest==8.3.5"

      - name: Install Playwright browsers
        run: python -m playwright install

      - name: Set BROWSER env
        run: echo "BROWSER=${{ matrix.browser }}" >> $Env:GITHUB_ENV

      - name: Run tests on ${{ matrix.browser }}
        run: pytest -q tests/zgoda_na_cookies.py