name: CI on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cookie-test:
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest playwright

      - name: Install Playwright browsers
        run: python -m playwright install

      - name: Run zgoda_na_cookies_for_automation.py on ${{ matrix.browser }}
        env:
          BROWSER: ${{ matrix.browser }}
        run: pytest -q zgoda_na_cookies_for_automation.py