name: Smoke CI

on:
  push:
    branches: [ main ]

jobs:
  install-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Ściągamy kod
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Ustawiamy Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Instalujemy zależności Pythona
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install greenlet>=3.0.3 playwright==1.52.0 pytest==8.3.5

      # 4. Instalujemy przeglądarki i biblioteki systemowe
      - name: Install Playwright browsers and deps
        run: |
          # zalecane: npx playwright install --with-deps
          npx playwright install --with-deps

      # 5. Wypisujemy zawartość cache, żeby upewnić się, że mamy chromium/firefox/webkit
      - name: List installed browsers
        run: |
          echo "→ ~/.cache/ms-playwright:"
          ls -R ~/.cache/ms-playwright || echo "  (brak katalogu!)"