name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      # 1. Ściągamy kod
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Ustawiamy Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Instalujemy zależności Pythona
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "greenlet>=3.0.3" "playwright==1.52.0" "pytest==8.3.5"

      # 4. Instalujemy przeglądarki i biblioteki systemowe
      - name: Install Playwright browsers and deps
        run: npx playwright install --with-deps

      # 5. Ustawiamy zmienną środowiskową BROWSER
      - name: Set BROWSER env
        run: echo "BROWSER=${{ matrix.browser }}" >> $GITHUB_ENV

      # 6. Odpalamy testy
      - name: Run tests on ${{ matrix.browser }}
        run: pytest -q tests/zgoda_na_cookies.py